In [36]:
from transformers import AutoTokenizer, AutoModelForMaskedLM, pipeline
import torch
from sklearn import linear_model
import sklearn
import numpy as np

In [22]:
tokenizer = AutoTokenizer.from_pretrained("huggingface/CodeBERTa-small-v1") 
#model = AutoModelForSequenceClassification.from_pretrained("huggingface/CodeBERTa-small-v1")
model = AutoModelForMaskedLM.from_pretrained("huggingface/CodeBERTa-small-v1")

In [110]:
entities = ['axes(0)$0','axes(0)$1','sentence(0)$1', 'next_chars(0)$1', 'sentence(0)$1']
entities_tokenize = tokenizer(entities, return_tensors="pt", padding=True, max_length=12, add_special_tokens=True)
#entities_embed = torch.flatten(model(entities_tokenize.input_ids)[0], start_dim=1).detach().numpy()
entities_embed = model(entities_tokenize.input_ids)[0].prod(dim=1).detach().numpy() 
#can also use sum - what does this mean?
entity_classes = [":Visualisation", ":Visualisation", ":Preparation", ":Preparation", ":Preparation"]

In [111]:
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(entities_embed, entity_classes, train_size = 0.8)

In [112]:
model(entities_tokenize.input_ids)[0].sum(dim=1).shape

torch.Size([5, 52000])

In [113]:
list(zip(entities, entities_embed, entity_classes))

[('axes(0)$0',
  array([ 2.5949137e+01, -1.2741293e+09, -2.6546636e-01, ...,
         -7.1670234e+03, -8.4931490e+06, -5.4967488e+04], dtype=float32),
  ':Visualisation'),
 ('axes(0)$1',
  array([ 6.0571175e+00, -8.6412717e+08, -4.1860542e-01, ...,
         -6.4152856e+02, -5.1567290e+06, -5.0530387e+04], dtype=float32),
  ':Visualisation'),
 ('sentence(0)$1',
  array([-8.1347668e-01, -1.3302588e+09, -1.2532225e+01, ...,
         -4.3899370e+03, -6.0681981e+05, -3.1451916e+04], dtype=float32),
  ':Preparation'),
 ('next_chars(0)$1',
  array([-6.2126046e-01, -3.9284653e+08,  8.3298569e+00, ...,
         -3.4356030e+03, -5.9399312e+05, -3.2863914e+03], dtype=float32),
  ':Preparation'),
 ('sentence(0)$1',
  array([-8.1345499e-01, -1.3302589e+09, -1.2532226e+01, ...,
         -4.3899395e+03, -6.0682012e+05, -3.1451877e+04], dtype=float32),
  ':Preparation')]

In [98]:
X_train.

(4, 468000)

array([[ 1.502286 , -9.33396  ,  0.5626838, ..., -1.3566533, -4.358929 ,
        -2.6980436]], dtype=float32)

In [70]:
ny

52000

In [106]:
clf = linear_model.LogisticRegression(random_state=0)
clf.fit(X_train, y_train)
list(zip(X_test,clf.predict(X_test)))



[(array([ -5.170274, -94.27469 ,  -4.342989, ..., -27.743105, -41.4804  ,
         -29.981155], dtype=float32),
  ':Preparation')]